export const GET_CONTACTS = 'GET_CONTACTS'
export const ADD_CONTACT = 'ADD_CONTACT'
export const ADD_CONTACT_WO_ACTION = 'ADD_CONTACT_WO_ACTION'

export const GET_BEERS_DONE = 'GET_BEERS_DONE'
export const GET_RANDOM_BEER_DONE = 'GET_RANDOM_BEER_DONE'
